BEGIN;
CREATE TABLE TELEFONE(
ID_TELEFONE NUMBER PRIMARY KEY,
DDD_TELEFONE NUMBER NOT NULL,
NUMERO NUMBER NOT NULL);


CREATE TABLE ENDERECO(
ID_ENDERECO NUMBER PRIMARY KEY,
NUMERO_ENDERECO NUMBER NOT NULL,
CEP_ENDERECO NUMBER NOT NULL,
COMPLEMENTO_ENDERECO VARCHAR(100) NOT NULL);

create table cliente(
ID_CLIENTE NUMBER PRIMARY KEY,
NOME_CLIENTE VARCHAR2(55) NOT NULL,
DT_NASCIMENTO_CLIENTE DATE NOT NULL,
SEXO_CLIENTE VARCHAR2(15) NOT NULL,
RG_CLIENTE VARCHAR2(10) NOT NULL,
CPF_CLIENTE VARCHAR2(11) NOT NULL,
FK_ENREDECO_CLIENTE NUMBER REFERENCES ENDERECO(ID_ENDERECO) NOT NULL,
FK_TELEFONE_CLIENTE NUMBER REFERENCES TELEFONE(ID_TELEFONE) NOT NULL,
EMAIL_CLIENTE VARCHAR2(120),
NATURALIDADE_CLIENTE VARCHAR2(55) NOT NULL,
ESCOLARIDADE_CLIENTE VARCHAR2(100) NOT NULL,
NOME_EMPRESA_CLIENTE VARCHAR2(55) NOT NULL,
RENDA_MENSAL_BRUTA_CLIENTE NUMBER NOT NULL);

create sequence c_cliente_seq
increment by 1
start with 1;

create sequence c_telefone_seq
increment by 1
start with 1;

create sequence c_endereco_seq
increment by 1
start with 1;

rollback;
commit;